version: 0.2


phases:

  build:
    commands:
      - docker run --rm -v $(pwd):/app -w /app composer install
      - mv .env.example .env
      - docker run --rm -v $(pwd):/app -w /app php:cli php artisan key:generate --ansi
      - docker run --rm -v $(pwd):/app -w /app phpunit/phpunit run
