version: 0.2
#env:
#  variables:
#parameter-store:
# key: "value"
# key: "value"

phases:
  install:
    commands:
      - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Expose apache.
#  EXPOSE 80
  pre_build:
    commands:
      - composer install
