version: 0.2


phases:

  build:
    commands:
      - docker run --rm --volume $PWD:/app composer install
      - php artisan key:generate --ansi
#      - docker run -v $(pwd):/app --rm phpunit/phpunit run
