version: '3'

services:
#  apache2:
#    build:
#      context: .
#      dockerfile: Dockerfile.apache2
#    image: laratwit_apache2:latest
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    image: laratwit_app:latest
    container_name: laratwit_app

    ports:
      - "80:80"
    #    volumes:
    #      - .././:/var/www/html
    environment:
      - "APP_ENV=production"
#      - "DB_HOST=database"
