version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    image: laratwit_app:latest
    container_name: laratwit_app

    ports:
      - "80:80"
    volumes:
      - ./:/app
    environment:
      - "APP_ENV=local"
