version: '3'

services:
  app:
    environment:
      - APP_DEBUG=0
      - APP_ENV=production
      - DB_CONNECTION=sqlite
    build:
      context: .
      dockerfile: Dockerfile.app
    image: laratwit_app:latest
    container_name: laratwit_app

    ports:
      - "80:80"
    volumes:
      - ./:/app # will be mounted on /var/www
# that the important thing
#volumes:
#  appcode-unison-sync:
#    external: true
